### ISSUE TITLE
Closed terminal

### ISSUE THREAD

**Issue by MasterCruelty** [MasterCruelty/Updater#43]
I would like to look for a way to open automatically a new terminal when the current closes because of the script such as in ```setup.sh``` and ```uninstall.sh```

**Comment by archetipico** [comment]
Since there are many terminals, and I don't think they all can be called with the same snippet (`gnome-terminal`, `terminator`, `xterm`,... tell me if I'm wrong), we should look for a way to reload `.bashrc`.

**Comment by archetipico** [comment]
I've solved it, I'm pushing on my branch.

**Comment by archetipico** [comment]
I'm looking for another solution, I don't like the one we have now

**Comment by MasterCruelty** [comment]
> I'm looking for another solution, I don't like the one we have now

Ok I'll see what you did
